

true_names = {
    "II" : "Irradiated Infantry",
    "Silo" : "Missile Silo",
    "Dozer" : "Dozer Tank",
    "Gatling" : "Gatling Tower",
    "EMP" : "Electromagnetic Pulse",
    "CC" : "Command Center",
    "Xolan" : "Sustainer Xolan",
    "Azure" : "Azure Reaper",
    "Mothership" : "Xeno Mothership",
    "Mother" : "Xeno Mothership",
    "Momship" : "Xeno Mothership",
    "Interceptor" : "Xeno Interceptor",
    "DH" : "Dominated Hatchlings",
    "Hatchling" : "Dominated Hatchlings",
    "Hatchlings" : "Dominated Hatchlings",
    "DomHatch" : "Dominated Hatchlings",
    "MC" : "Mind Controller",
    "Sharpie" : "Sharpshooter",
    "Raptor" : "Venomous Raptor",
    "LoT" : "Lord of Tartarus",
    "Drac" : "Dracorex",
    "MB" : "Mortar Bunker",
    "Mortar" : "Mortar Bunker",
    "Bunker" : "Mortar Bunker",
    "Loki" : "Loki's Scion",
    "Scion" : "Loki's Scion",
    "Niaq" : "Stealthy Niaq",
    "Stealthy" : "Stealthy Niaq",
    "Analyzer" : "Remote Analyzer",
    "DQ" : "Draconian Queen",
    "Queen" : "Draconian Queen",
    "Draconian" : "Draconian Queen",
    "DQueen" : "Draconian Queen",
    "Pumm" : "Pummeller",
    "Pool" : "Blood Pool",
    "Spout" : "Blood Spout",
    "Bolster" : "Bolster Xeno",
    "BX" : "Bolster Xeno",
    "Quaker" : "World Quaker",
    "WQ" : "World Quaker",
    "Tox Cannon" : "Toxic Cannon",
    "Toxic" : "Toxic Cannon",
    "Tox" : "Toxic Cannon",
    "EQG" : "Earthquake Generator",
    "Tesla" : "Tesla Cannon",
    "CW" : "Cannon Walker",
    "Bolide" : "Bolide Walker",
    "Shifter" : "Shapeshifter",
    "MH" : "Metalhead",
    "Leo" : "T-46 Leonidas",
    "Leonidas" : "T-46 Leonidas",
    "MW" : "Mech Walker",
    "InvasionCo" : "Invasion Coordinator",
    "InvCo" : "Invasion Coordinator",
    "IC" : "Invasion Coordinator",
    "Demo Bot" : "Demolition Bot",
    "EM" : "Enforcer Mech",
    "EMech" : "Enforcer Mech",
    "ComSat" : "ComSat Terminal",
    "Overlord" : "Xeno Overlord",
    "AS" : "Absorption Shield",
    "AbsShield" : "Absorption Shield",
    "TI" : "Tactical Infiltrator"
    }

preferred_aliases = {
    "Irradiated Infantry" : "II",
    "Missile Silo" : "Silo",
    "Dozer Tank" : "Dozer",
    "Gatling Tower" : "Gatling",
    "Electromagnetic Pulse" : "EMP",
    "Command Center" : "CC",
    "Sustainer Xolan" : "Xolan",
    "Azure Reaper" : "Azure",
    "Xeno Mothership" : "Mothership",
    "Xeno Interceptor" : "Interceptor",
    "Dominated Hatchlings" : "Hatchling",
    "Mind Controller" : "MC",
    "Sharpshooter" : "Sharpie",
    "Venomous Raptor" : "Raptor",
    "Lord of Tartarus" : "LoT",
    "Dracorex" : "Drac",
    "Mortar Bunker" : "MB",
    "Loki's Scion" : "Loki",
    "Stealthy Niaq" : "Niaq",
    "Remote Analyzer" : "Analyzer",
    "Draconian Queen" : "DQ",
    "Pummeller" : "Pumm",
    "Blood Pool" : "Pool",
    "Blood Spout" : "Spout",
    "Bolster Xeno" : "Bolster",
    "Toxic Cannon" : "Tox Cannon",
    "Earthquake Generator" : "EQG",
    "Tesla Cannon" : "Tesla",
    "Cannon Walker" : "CW",
    "Bolide Walker" : "Bolide",
    "Shapeshifter" : "Shifter",
    "Metalhead" : "MH",
    "T-46 Leonidas" : "Leo",
    "Invasion Coordinator" : "InvasionCo",
    "Demolition Bot" : "Demo Bot",
    "Enforcer Mech" : "EMech",
    "ComSat Terminal" : "ComSat",
    "Xeno Overlord" : "Overlord",
    "Tactical Infiltrator" : "TI"
}


class CardAliases:

    @staticmethod
    def true_name(alias):
        return true_names[alias] if alias in true_names else alias

    @staticmethod
    def preferred_name(true_name):
        return preferred_aliases[true_name] if true_name in preferred_aliases else true_name
